#include "marisa-wrap.hpp"


NAN_MODULE_INIT(MarisaWrap::Init) {
  AgentWrap::Init(target);
  KeyWrap::Init(target);
  KeysetWrap::Init(target);
  QueryWrap::Init(target);
  TrieWrap::Init(target);

#define TEMP_SET_CONSTINT(name) \
  Nan::Set(target, Nan::New(#name).ToLocalChecked(), Nan::New(MARISA_ ## name))

  TEMP_SET_CONSTINT(MIN_NUM_TRIES);
  TEMP_SET_CONSTINT(MAX_NUM_TRIES);
  TEMP_SET_CONSTINT(DEFAULT_NUM_TRIES);

  TEMP_SET_CONSTINT(HUGE_CACHE);
  TEMP_SET_CONSTINT(LARGE_CACHE);
  TEMP_SET_CONSTINT(NORMAL_CACHE);
  TEMP_SET_CONSTINT(SMALL_CACHE);
  TEMP_SET_CONSTINT(TINY_CACHE);
  TEMP_SET_CONSTINT(DEFAULT_CACHE);

  TEMP_SET_CONSTINT(TEXT_TAIL);
  TEMP_SET_CONSTINT(BINARY_TAIL);
  TEMP_SET_CONSTINT(DEFAULT_TAIL);

  TEMP_SET_CONSTINT(LABEL_ORDER);
  TEMP_SET_CONSTINT(WEIGHT_ORDER);
  TEMP_SET_CONSTINT(DEFAULT_ORDER);

  TEMP_SET_CONSTINT(NUM_TRIES_MASK);
  TEMP_SET_CONSTINT(CACHE_LEVEL_MASK);
  TEMP_SET_CONSTINT(TAIL_MODE_MASK);
  TEMP_SET_CONSTINT(NODE_ORDER_MASK);
  TEMP_SET_CONSTINT(CONFIG_MASK);

#undef TEMP_SET_CONSTINT
}
